add Cloud DNS SSL config
cdr/docs pull request #269
Opened 2021-04-12 23:01 UTC by ericpaulsen

adding steps for configuring SSL for Coder via Google's Cloud DNS, referenced from [this doc](https://docs.google.com/document/d/1NahF4Mx5t_nLrwg7MZsyeSlMVnEIQi29v7poNl6LV8w/edit#).

please see my comments below for line-specific thoughts.

2021-04-12 23:03 UTC, ericpaulsen commented on guides/ssl-certificates/cloudDNS.md
> +- A Kubernetes cluster with internet connectivity
`cert-manager` supports 1.16+ K8s versions, but I could not find any Cloud DNS-specific version compatibilities. This doc also assumes that a customer has a Service Account configured.

2021-04-12 23:03 UTC, ericpaulsen commented on guides/ssl-certificates/cloudDNS.md
> +## Step 1: Add cert-manager to your Kubernetes cluster
If needed, feel free to add context around applying the `cert-manager` manifest.

2021-04-12 23:04 UTC, ericpaulsen commented on guides/ssl-certificates/route53.md
> +  --set ingress.tls.devUrlsHostSecretName=devUrlCertificate \
typo fix.

2021-04-13 02:39 UTC, bpmct requested changes
This is awesome Eric!

I think this also needs to be added to the manifest.json so that it is added in https://codercom-2h12dwib3-codercom.vercel.app/docs/guides/ssl-certificates

2021-04-13 02:39 UTC, bpmct commented on guides/ssl-certificates/cloudDNS.md
> +  [Service Account](https://cloud.google.com/iam/docs/creating-managing-service-accounts)
```suggestion
  [GCP Service Account](https://cloud.google.com/iam/docs/creating-managing-service-accounts) with the `dns.admin` role
```

2021-04-13 02:40 UTC, bpmct commented on guides/ssl-certificates/cloudDNS.md
> +  [Service Account](https://cloud.google.com/iam/docs/creating-managing-service-accounts)
context: https://cert-manager.io/docs/configuration/acme/dns01/google/#set-up-a-service-account

2021-04-14 19:49 UTC, khorne3 approved these changes

2021-04-14 21:14 UTC, merged