Explain install.sh must be executable
cdr/docs pull request #319
Opened 2021-05-04 13:44 UTC by brianbegy

Add a sentence explaining that the install.sh must be marked executable and that coder won't do it for you.

I was assuming that coder would mark as executable anything it intended to execute.  That is not the case.

2021-05-04 14:11 UTC, IAmHughes requested changes
@khorne3 let me know if you prefer this format. I think we should at least put `install.sh` in code tags but I'm not convinced on the `Note` prefix I added

2021-05-04 14:11 UTC, IAmHughes commented on workspaces/personalization.md
> +You must mark the install.sh file as executable before committing it to your dotfiles repo.
```suggestion
- _Note: You must mark the `install.sh` file as executable before committing it to your dotfiles repo._
```

Just a minor suggestion on formatting

2021-05-04 14:31 UTC, brianbegy commented on workspaces/personalization.md
> +You must mark the install.sh file as executable before committing it to your dotfiles repo.
That makes sense.

2021-05-04 14:32 UTC, khorne3 approved these changes

2021-05-04 14:37 UTC, merged

2021-09-16 14:10 UTC, vapurrmaid commented
@all-contributors please add @brianbegy  for content