Release 1.21.0
cdr/docs pull request #467
Opened 2021-07-06 20:50 UTC by khorne3

## Release Checklist

- [ ] All Feature documentation merged
- [ ] Changelog completed
- [ ] Technical Engineer Review
- [ ] Documentation Owner Review
- [ ] Release Manager Review
- [ ] Commit cleaned up and co-authored

2021-07-22 15:06 UTC, Emyrk commented on admin/satellites/management.md
> +helm add coder https://helm.coder.com
```suggestion
helm repo add coder https://helm.coder.com
```

2021-07-26 17:33 UTC, bpmct requested changes
I noticed a few things in our current docs that need to be updated for 1.21. Tracking these here and can submit PRs to this branch to resolve if nobody beats me to it :)

- [x] everything that mentions cemanager is now coderd (ex. the reset password command)
- [x] places that mentions helm values should probably be evaluated (e.x SSH access is now enabled/disabled in the workspace providers page, not helm)
- [x] install page says to look for ingress-nginx IP. new installs on 1.21 do not include an ingress

I'm sure there are also more, I did not do a comprehensive search. These are just some things I've observed using the RC for various things

2021-07-26 18:04 UTC, khorne3 commented
needs https://github.com/cdr/docs/pull/512 and https://github.com/cdr/docs/pull/511

2021-07-27 20:12 UTC, deansheather commented on changelog/1.21.0.md
> +  UI.
This is not a breaking change, legacy workspace providers still have the ping indicator. The ping indicator is only missing for net v2 enabled providers.

2021-07-27 20:12 UTC, deansheather commented on changelog/1.21.0.md
> +- infra: Added connection cache based on open DataChannels.
```suggestion
```

2021-07-27 20:12 UTC, deansheather commented on changelog/1.21.0.md
> +- web: Added ability to enable/disable SSH access to the edit workspace
This is called "External Connect" and blocks SSH and external tunneling (except for devurls)

2021-07-27 20:12 UTC, deansheather commented on changelog/1.21.0.md
> +- infra: Added functionality so Coder agent output is written to logs.
```suggestion
```

2021-07-27 20:12 UTC, deansheather commented on changelog/1.21.0.md
> +- web: Removed appProtocol from `coderd`.
```suggestion
```

2021-07-27 20:12 UTC, deansheather commented on changelog/1.21.0.md
> +- web: Fixed issue with envproxy routes to resolve broken PWA bookmarks.
This should be a feature (or just removed entirely)
```
- web: Redirect legacy envproxy routes to the new NetworkingV2 routes to keep bookmarks.
```

2021-07-27 20:29 UTC, deansheather approved these changes

2021-07-27 20:35 UTC, merged