feat: Add mobile Android development docs
cdr/docs pull request #69
Opened 2021-01-29 03:43 UTC by kylecarbs

**Don't merge until 1.16.0 releases.** We need to support local -> remote port forwarding, and we don't in the latest released version.

2021-01-29 03:52 UTC, cmoog requested changes

2021-01-29 03:52 UTC, cmoog commented on environments/mobile-development.md
> +   `ssh -R 5555:127.0.0.1:5555 coder.<env name>`
first link to SSH setup docs

2021-01-29 04:59 UTC, nathanpotter commented on environments/mobile-development.md
> +1. Set the installation path of your Android SDK to the environment variable `ANDROID_SDK_PATH`.
Would be good to show how to get to this preferences page to find this value, maybe something like:
Preferences > System Settings > Android SDK

2021-01-29 04:59 UTC, nathanpotter commented on environments/mobile-development.md
> +1. Set the installation path of your Android SDK to the environment variable `ANDROID_SDK_PATH`.
This statement was a bit confusing as I went through it – are you telling me to set this config page option to `ANDROID_SDK_PATH` or are you saying go into your terminal and set an environment variable named `ANDROID_SDK_PATH` to the sdk path value that you found in this prefs page?

2021-01-29 05:00 UTC, nathanpotter commented on environments/mobile-development.md
> +   ./gradlew android:installDebug
I didn't have any android code in my remote env, so this didn't do anything for me – may be good to show users how to transition their source code to being remote as well, potentially w/ coder sync

2021-01-29 22:57 UTC, bpmct commented
I think we should add a "developer guides" section that supports stuff like this. I'm working on similar stuff that I'd love to put in docs.

2021-02-22 15:24 UTC, khorne3 commented
@kylecarbs Is this still going out with 1.16? If so, I can fix and merge it into the docs branch for the release

2021-02-22 17:23 UTC, kylecarbs commented
That'd be awesome @khorne3 !

2021-02-22 19:13 UTC, merged